// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxfzmirlhxqcbdtodyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeGZ6bWlybGh4cWNiZHRvZHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzcyNjQsImV4cCI6MjA2NzMxMzI2NH0.24wRh7VIXEJMq55Hg7KI5fgRYWg0_VSPmZiG5GvFHic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});